import type { Metadata } from "next";
import UseApp from "./UseApp";
import 'react-tooltip/dist/react-tooltip.css'
import "./globals.css";

export const metadata: Metadata = {
  title: "Kiosko Cristi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <UseApp>
          {children}
        </UseApp>
      </body>
    </html>
  );
}
